In [85]:
#do these manually as each has a different format, only need the filenames

In [86]:
import pandas as pd 
import os
#need this to see the full column width
pd.set_option('display.max_colwidth', None)

In [96]:
data_dir = '../test_data/Luis_fileLists'
# os.path.join(data_dir,fName)

In [98]:
# files = [f for f in os.listdir('.') if f.endswith('.txt')]
files = [f for f in os.listdir(data_dir) if f.endswith('.txt')]

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../test_data/Luis_fileLists'

In [99]:
os.getcwd()

'd:\\dropbox\\github_niskin\\SargassoDB\\test_data\\Luis_fileLists'

In [88]:
files

['only_in_cyverse.txt', 'only_in_gdrive.txt', 'overlap.txt']

In [89]:
df = pd.read_csv('only_in_cyverse.txt',sep='\t',header=None,comment = '#',names = ['filename'])

#strip off the end of the filename
for index,row in df.iterrows():
    #file = os.path.basename(row.to_string()).strip('.gz')
    file = os.path.basename(row['filename'])
    df.loc[index,'filename'] = file

df['source'] = 'cyverse'
df_co = df

In [90]:
df_co.head()

                                                         filename   source
0    lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R1_001.fastq.gz  cyverse
1    lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R2_001.fastq.gz  cyverse
2  lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R1_001.fastq.gz  cyverse
3  lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R2_001.fastq.gz  cyverse
4    lane1-s003-index--CTCTAGAG-TACGAGAC-148-0_S3_R1_001.fastq.gz  cyverse

In [91]:
df = pd.read_csv('only_in_gdrive.txt',sep='\t',header=None,comment = '#',names = ['filename'])
#strip off the end of the filename
for index,row in df.iterrows():
    #file = os.path.basename(row.to_string()).strip('.gz')
    #file = os.path.basename(df.loc[0,'filename']).strip('.gz')
    file = os.path.basename(row['filename'])
    df.loc[index,'filename'] = file
df['source'] = 'google'
df_go = df
df_go.head()

                                         filename  source
0    1032901105-AE1624-80_S3_L001_R2_001.fastq.gz  google
1  1032901603-AE1624-600_S10_L001_R1_001.fastq.gz  google
2  1033101511-AE1629-200_S25_L001_R2_001.fastq.gz  google
3  1033201521-AE1701-800_S39_L001_R1_001.fastq.gz  google
4     1033300401-EN592-1_S41_L001_R1_001.fastq.gz  google

In [92]:
#for the overlap I only need the filename
df = pd.read_csv('overlap.txt',sep='\t',header=None,comment = '#',names = ['filename','cyPath','gPath'])
df = df.drop(columns = ['cyPath','gPath'])
df['source']='cyANDgoogle'
df_o = df

In [93]:
result = pd.concat([df_o,df_co,df_go])

In [94]:
result.to_csv('filelist_concatenated.csv')