In [13]:
#do these manually as each has a different format, only need the filenames

In [14]:
import pandas as pd 
import os
#need this to see the full column width
pd.set_option('display.max_colwidth', None)

In [15]:
dataDir = '../test_data/Luis_fileLists'
files = [f for f in os.listdir(dataDir) if f.endswith('.txt')]

In [16]:
files

['only_in_cyverse.txt', 'only_in_gdrive.txt', 'overlap.txt']

In [17]:
df = pd.read_csv(os.path.join(dataDir,'only_in_cyverse.txt'),sep='\t',header=None,comment = '#',names = ['filename'])

#strip off the end of the filename
for index,row in df.iterrows():
    #file = os.path.basename(row.to_string()).strip('.gz')
    file = os.path.basename(row['filename'])
    df.loc[index,'filename'] = file

df['source'] = 'cyverse'
df_co = df

In [18]:
df_co.head()

                                                         filename   source
0    lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R1_001.fastq.gz  cyverse
1    lane1-s001-index--CTCTAGAG-CGTTACTA-147-0_S1_R2_001.fastq.gz  cyverse
2  lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R1_001.fastq.gz  cyverse
3  lane1-s002-index--CTCTAGAG-AGAGTCAC-147-200_S2_R2_001.fastq.gz  cyverse
4    lane1-s003-index--CTCTAGAG-TACGAGAC-148-0_S3_R1_001.fastq.gz  cyverse

In [19]:
df = pd.read_csv(os.path.join(dataDir,'only_in_gdrive.txt'),sep='\t',header=None,comment = '#',names = ['filename'])
#strip off the end of the filename
for index,row in df.iterrows():
    #file = os.path.basename(row.to_string()).strip('.gz')
    #file = os.path.basename(df.loc[0,'filename']).strip('.gz')
    file = os.path.basename(row['filename'])
    df.loc[index,'filename'] = file
df['source'] = 'google'
df_go = df
df_go.head()

                                         filename  source
0    1032901105-AE1624-80_S3_L001_R2_001.fastq.gz  google
1  1032901603-AE1624-600_S10_L001_R1_001.fastq.gz  google
2  1033101511-AE1629-200_S25_L001_R2_001.fastq.gz  google
3  1033201521-AE1701-800_S39_L001_R1_001.fastq.gz  google
4     1033300401-EN592-1_S41_L001_R1_001.fastq.gz  google

In [20]:
#for the overlap I only need the filename
df = pd.read_csv(os.path.join(dataDir,'overlap.txt'),sep='\t',header=None,comment = '#',names = ['filename','cyPath','gPath'])
df = df.drop(columns = ['cyPath','gPath'])
df['source']='cyANDgoogle'
df_o = df

In [21]:
result = pd.concat([df_o,df_co,df_go],ignore_index=True)

In [22]:
def trimSuffix(one):
    one = one.removesuffix('.gz').removesuffix('.fastq').removesuffix('_fastqc.html').removesuffix('_fastqc.zip')      
    return one

In [23]:
for index,row in result.iterrows():
    result.loc[index,'filename'] = trimSuffix(result.loc[index,'filename'])

In [24]:
#result.to_csv(os.path.join(dataDir,'filelist_concatenated.csv'))
result.to_csv('../test_data/filelist_concatenated.csv')

In [25]:
#misc scripting check (just a place to easily use Python)

In [26]:
# one = 'lane1-s001-indexN716-B-S502-B-ACTCGCTA-CTCTCTAT-BS342_S1_L001_R1_001_fastqc.html'
one = 'lane1-s001-indexN716-B-S502-B-ACTCGCTA-CTCTCTAT-BS342_S1_L001_R1_001_fastqc.zip'

In [27]:
def trimSuffix(one):
    one = one.removesuffix('.gz').removesuffix('.fastq').removesuffix('_fastqc.html').removesuffix('_fastqc.zip')    
    return one

In [28]:
trimSuffix(one)

'lane1-s001-indexN716-B-S502-B-ACTCGCTA-CTCTCTAT-BS342_S1_L001_R1_001'